### ISSUE TITLE
Issues about the patch embedding.

### ISSUE THREAD

**Issue by ddghjikle** [JingyunLiang/SwinIR#14]
Hi, thanks very much for sharing this wonderful work. According to the definition of PatchEmbed(nn.Module). It seems that the parameters such as patch_size and img_size are not used. It seems  that performance improvements of SwinIRs are provided by these MAS and MLP layers. Of course, multiple skip connections in the RSTB and STL are also helpful. I am curious about why the SwinIRs do not form patches with multiple pixels. For example, the PatchEmbed method used in 
《Pyramid Vision Transformer: A Versatile Backbone for Dense Prediction without Convolutions》.

**Comment by JingyunLiang** [comment]
Your idea deserves a try. To be honest, I didn't try it because I believe image restoration is a very local problem. We should process the image pixel by pixel (attention between pixels). From my intuition, there should have a performance drop if we process them patch by patch (attention between patches such as what IPT does).

However, it can reduce the computation burden if we do so. You can try to use it and see the results.

**Comment by JingyunLiang** [comment]
Feel free to open it if you have more questions.
