### ISSUE TITLE
about test

### ISSUE THREAD

**Issue by jiaaihhy** [JingyunLiang/SwinIR#35]
在swinIR模型中，有img_size这个参数，例如为128， 在SwinLayer时，是input_resolution=（128， 128）, 比如我在测试的时候，我的输入图像不是(128, 128) 那么计算attention的时候 有一个判断， if self.input_resolution == x_size， else attn_windows = self.attn(x_windows, mask=self.calculate_mask(x_size).to(x.device))。我想请问一下如果图片大小不等于self.input_resolution=(128,128)时， 加入的参数 mask 这个是什么mask

**Comment by JingyunLiang** [comment]
See https://github.com/JingyunLiang/SwinIR/issues/9 for a discussion

**Comment by jiaaihhy** [comment]
可是还是没有解决这个问题，我还是不理解如果input_resolution != x_size加的这个mask是什么 以及为什么要加这个mask
         if self.input_resolution == x_size:
            attn_windows = self.attn(x_windows, mask=self.attn_mask)  # nW*B, window_size*window_size, C
        else:           
             attn_windows = self.attn(x_windows, mask=self.calculate_mask(x_size).to(x.device))
https://github.com/JingyunLiang/SwinIR/blob/b28be97c69b8f5a6c32a0adf864afa7375edba11/models/network_swinir.py#L262

**Comment by jiaaihhy** [comment]
verythanks

**Comment by JingyunLiang** [comment]
This line is for training. We initialize the mask as `self.attn_mask` so that we don't need to calculate the mask for every iteration.  Note that the training image size is fixed, e.g., 64x64.
https://github.com/JingyunLiang/SwinIR/blob/b28be97c69b8f5a6c32a0adf864afa7375edba11/models/network_swinir.py#L259
This line is for testing. We calculate the mask for a given testing image. Note that the testing image is generally not 64x64.
https://github.com/JingyunLiang/SwinIR/blob/b28be97c69b8f5a6c32a0adf864afa7375edba11/models/network_swinir.py#L261

**Comment by jiaaihhy** [comment]
when test, what is the  meaning of the mask? thankyou

**Comment by JingyunLiang** [comment]
Similar to training, we pad the image after shifting it. You can try not using padding during testing and share the results with me. Thank you.

**Comment by JingyunLiang** [comment]
Yes, attn_mask is only used for those transformers that operate on shifted window. Imagine that for a 64x64 input, after shifting 4x4 pixels towards top-left corner (by using `torch.roll`), pixels within [0:4,:] and [:,0:4] are shifted to [60:64,:] and [:,60:64], respectively. In such a case, pixels within [56:60,:] and [:,56:60] will be forced to attend to above **unrelated pixels** after the new window partition. This is not we want, so we use attn_mask to mask them out.

**Comment by paragon1234** [comment]
This is an interesting point, from an implementation perspective. I am wondering what if we simply not do self-attention on pixels within [56:64,:] and [:,56:64] for shifter_windows ? 
    On a much detailed look: why should transformer operate only on [56:60,:] and [:,56:60], but not on [0:4,:] and [:,0:4]? What if transformer operate on both, without mixing them ie even smaller window size?

**Comment by JingyunLiang** [comment]
I didn't test these two cases, but I guess the first case may lead to slightly worse performance (this part of data is discarded), while the second one may leads to slightly better performance (making full use of this part of data). The current implementation is just for simplicity and efficiency.

**Comment by JingyunLiang** [comment]
Feel free to open it if you have more questions.

**Comment by paragon1234** [comment]
Can you please explain why we need mask for testing, when input resolution is not 48x48?
`I tried to change the attention mechanism in the code. However, my method did not require mask. I removed calculate_mask from code and completed the training phase. However, during testing it gave error.`
My concern is: 1)Do I require mask in my attention? 2)How to change my attention mechanism to incorporate mask?

**Comment by JingyunLiang** [comment]
SwinIR needs mask for either input resolution of 48x48 or not. The difference is that we use pre-calculated mask for 48x48 images because we store it in the `.pth` file during training. For non 48x48 images, we need to recompute it.

For the second concern, what is your error in testing? If you don't need mask in your own attention, there is no need for masking in testing as well. Sorry that I cannot give more help because I don't you what is your `changed attention mechanism`.

**Comment by paragon1234** [comment]
I am using tth model: efficient attention(https://github.com/cmsflash/efficient-attention). 
I do not understand why we require mask? Even for 48x48 patch, as per your last reply? 
Also, the training-time is more compared to swinIR. Maybe the window_size of 8x8 is super efficient for low-level image processing.

**Comment by JingyunLiang** [comment]
It seems that the position encoding is not very important for SR from my experience. You can try to remove it and compare their results. Note the it may be trick to apply masks for efficient attention (see https://github.com/cmsflash/efficient-attention/issues/4)
